"""
ai_quant_analyst/report_generator.py
─────────────────────────────────────
Institutional Report Generator.
Formats quantitative analysis, risk metrics, SHAP explanations, and advisor recommendations into institutional investment memos.
"""

from __future__ import annotations
import json
import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional
import pandas as pd

from ai_quant_analyst.config import AIAnalystConfig

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Assembles institutional investment reports, tearsheets, and executive memos.
    """

    def __init__(self, config: Optional[AIAnalystConfig] = None):
        self.config = config or AIAnalystConfig()

    def build_investment_report(
        self,
        strategy_name: str,
        predictions_explanation: Optional[Dict[str, Any]] = None,
        shap_explanation: Optional[Dict[str, Any]] = None,
        risk_analysis: Optional[Dict[str, Any]] = None,
        recommendations: Optional[List[Dict[str, str]]] = None,
        backtest_metrics: Optional[Dict[str, Any]] = None,
    ) -> str:
        """
        Builds a comprehensive Markdown investment report.

        Returns:
            Formatted Markdown report string.
        """
        lines = [
            f"# 📊 Institutional Investment Report: {strategy_name}",
            f"**Author:** {self.config.analyst_name}  ",
            f"**Report Style:** {self.config.style.capitalize()}  ",
            "---",
            "",
            "## 1. Executive Summary",
        ]

        if backtest_metrics:
            cagr = backtest_metrics.get("cagr", 0.0)
            sharpe = backtest_metrics.get("sharpe_ratio", 0.0)
            max_dd = backtest_metrics.get("max_drawdown", 0.0)
            lines.append(
                f"Strategy **{strategy_name}** achieved a **CAGR of {cagr:.2%}** with a **Sharpe Ratio of {sharpe:.2f}** "
                f"and a **Max Drawdown of {max_dd:.2%}**."
            )
        else:
            lines.append(f"Comprehensive quantitative audit for strategy **{strategy_name}**.")

        lines.append("")

        # ── 2. Model Prediction & SHAP Analysis ─────────────────────────────
        if predictions_explanation or shap_explanation:
            lines.append("## 2. Quantitative Prediction & SHAP Attribution")
            if predictions_explanation:
                lines.append(f"### Prediction Insight: {predictions_explanation.get('symbol', 'Portfolio')}")
                lines.append(f"> {predictions_explanation.get('narrative', '')}")
                lines.append("")

            if shap_explanation:
                lines.append("### Top SHAP Feature Attributions")
                lines.append(f"```text\n{shap_explanation.get('full_breakdown', '')}\n```")
                lines.append("")

        # ── 3. Risk & Resilience Audit ──────────────────────────────────────
        if risk_analysis:
            lines.append("## 3. Risk & Resilience Profile")
            lines.append(f"**Overall Risk Grade:** `{risk_analysis.get('risk_grade', 'N/A')}`")
            lines.append(f"> {risk_analysis.get('overall_assessment', '')}")
            lines.append("")

            sections = risk_analysis.get("sections", {})
            for title, content in sections.items():
                lines.append(f"#### {title}")
                lines.append(f"{content}\n")

            alerts = risk_analysis.get("alerts", [])
            if alerts:
                lines.append("⚠️ **Active Risk Alerts:**")
                for a in alerts:
                    lines.append(f"- {a}")
                lines.append("")

        # ── 4. Strategic Recommendations ───────────────────────────────────
        if recommendations:
            lines.append("## 4. Prioritized Recommendations")
            for rec in recommendations:
                prio = rec.get("priority", "LOW")
                icon = "🔴" if prio in ["HIGH", "CRITICAL"] else "🟡" if prio == "MEDIUM" else "🟢"
                lines.append(f"### {icon} [{prio}] {rec.get('domain', 'GENERAL')}")
                lines.append(f"**Action:** {rec.get('recommendation', '')}")
                lines.append(f"**Rationale:** {rec.get('rationale', '')}\n")

        lines.append("---")
        lines.append(f"*Generated by {self.config.analyst_name}. Proprietary & Confidential.*")

        return "\n".join(lines)

    def export_report(
        self,
        report_text: str,
        output_path: str = "reports/investment_report.md",
    ) -> str:
        """Saves report text to disk."""
        Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report_text)
        logger.info(f"[ReportGenerator] Exported investment report to {output_path}")
        return output_path
